:PROPERTIES:
:ID:       067059f6-be3d-4994-86ca-d7d33a291a79
:END:
#+title:    Muse
#+filetags: :DND:bard:
#+author:   zfoteff
#+date:     [2023-07-12 Wed]
#+summary:  Bard class summary
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../static/stylesheets/subclass-style.css" />
#+BEGIN_CENTER
[[[id:7d419730-2064-41f9-80ee-f24ed9b01ac7][Main Menu]]] [[[id:69ef1740-156a-4e42-9493-49ec80a4ac26][Classes]]] [[[id:8bb9a08a-97c0-4231-a002-ad7dcf83e4d8][Bard]]]
#+END_CENTER
-----
* Level 1
- Gain the ability to play two instruments of you choice
- You may occasionally encounter musicians throughout the world, who will potentially grant you phenomenal rewards if you play in jam sessions with them. Only muses can play in Divine Jams
- Gain an enchanted instrument of your choice. This deals 1d6 damage to all enemies within earshot when played, and can be further enchanted to increase its power.
* Level 2
- Obtain an eternal, irrevocable, and unchangeable cultural side-quest from the Cultural Side-Quest Generator. Completion of the side-quest may result in additional awards, and will 1 result in the player being rewarded another cultural side-quest.
- Gain _Hypnosis_: You may attempt to Hypnotize low-Intelligence [fn:1] creatures while playing an instrument. While hypnotized, they are susceptible to your commands for 3 turns.
* Level 5
- Your enchanted instrument's base damages increases to 1d8.
* Level 10
- Gain _Spectral Manager_: The manager will keep you informed of any important cultural and political requests upon request. It may also send you concert invites, and give you a hookup for drugs.
- Gain _Booking Agent_: Once per long rest, you many travel to any part of the world in a single day, and the agent will arrange travel free of cost.
* Level 15
- Gain a Patron Demigod. One of the Demigods will adopt you as their muse, and once every 3 combat sessions, you may summon the Demigod to assist you. Note: that not all Demigods are good fighters. Patron Demigods are automatically reassigned upon the death of the player's previous Demigod. Do with that what you will. There may be consequences if you disappoint your Patron with the music you play.
* Level 19
- Gain knowledge of the _*Eldrich Tune*_: Upon playing the Eldrich Tune to completion, one of the Old Gods will descend upon you to initiate an end-game level encounter. This will result in significant rewards for the actor, and potentially other players in the party.
* Footnotes
[fn:1] Glossary: [[id:a3719559-2b06-443a-b75a-96c9aa3f3b26][Intelligence]]
