:PROPERTIES:
:ID:       569f7d4d-5744-49e4-ac0d-bebbd1795992
:END:
#+title:    Psychic Sorcerer
#+filetags: :DND:sorcerer:
#+author:   zfoteff
#+date:     [2023-07-17 Mon]
#+summary:  Psychic sorcerer
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../static/stylesheets/subclass-style.css" />
#+BEGIN_CENTER
[[[id:7d419730-2064-41f9-80ee-f24ed9b01ac7][Main Menu]]] [[[id:69ef1740-156a-4e42-9493-49ec80a4ac26][Classes]]] [[[id:f2323133-e17d-4cff-86db-415b72e6d42e][Sorcerer]]]
#+END_CENTER
-----
Something in your mind has unhinged, and in an absolute fluke this has unlocked a hidden magic that lies within the minds and hearts of all beings.

* Sorcerer Traits
- /Gift of Gab/: For one reason or another, you're a enthralling speaker. Your persuasion attempts have advantage
- /Schizoid/:
* Level 1 Sorceries
- _*Migraine*_: Roll to hit. On hit, give a target a headache for three turns. Deal 1d8 madness damage on the first turn, 1d6 psychic damage, and 1d4 psychic damage.
- _*Cursed Knowledge*_: Allow a party member to glimpse the insanity. Give this member +4 insight for the whole turn.
- _*Discordant Whisper*_: You whisper a discordant melody that only one creature of your choice within range can hear, wracking it with terrible pain. The target must make a Wisdom saving throw. On a failed save, it takes 3d6 psychic damage and must immediately use its reaction, if available, to move as far as its speed allows away from you. The creature doesn’t move into obviously dangerous ground, such as a fire or a pit. On a successful save, the target takes half as much damage and doesn’t have to move away. A deafened creature automatically succeeds on the save.
* Level 2 (5+) Sorceries
- _*Jedi Mind Trick*_: You know the rules. This automatically succeeds on every creature with less than 13 INT. Creatures at or above 13 INT must roll a INT saving throw. /The extent of this ability is up to DM discretion/
- _*Bad Memory*_: Force a target to make a WIS saving throw. On fail, they take 1d8 madness damage and attempt to run away and cry. If they cannot run away (due to stun, root, etc), they take an additional 2d8 madness damage
- _*Confuse*_: Force a target to make a WIS saving throw. On fail, their next attack is against a random target in combat and the attack does half damage.
* Level 3 (11+) Sorceries
- _*Mind Reader*_: Twice per long rest, discern the exact intentions of a creature as well as one additional fact about them. This ability can be used only when engaged in conversation with the subject.
- _*Delirium*_: Once per combat, force a target to make a CON saving throw. On failure, the target attacks one member of their party (or themselves if alone), run away, and suffer the effects of madness for a turn.
* Level 4 (15+) Sorceries
- _*Mind Control*_: Force any creature but one of the gods to make a WIS, CON, and INT saving throw. The extent to which you mind control this person depends on how many of the saving throws they succeed on. From then on, the creature will do you bidding (/with some DM intervention/). Gain one charge every 2 long rests.
- _*Mass Hallucination*_: Change one facet of history forever. The practical outcome of the event will remain the same, but everyone will remember the event differently. How different will depend on how you'd like to change the event.
