:PROPERTIES:
:ID:       campaign-classes
:END:
#+title     Campaign Classes
#+author:   zfoteff
#+date:     [2023-07-03 Mon]
#+summary:  Campaign classes submenu

* [[id:8bb9a08a-97c0-4231-a002-ad7dcf83e4d8][Bard]]
* Druid
Work with the forces of nature to pursue your goals. Use alchemy primarily, cast using Charisma
* [[id:3e1b93b3-f1ad-4148-bb16-5313b376a707][Wizard]]
* Monk
Trust only in a higher power(s?) to achieve your goals. Uses weapons and unarmed strikes primarily.
* Sorcerer
Manipulate the world around you in a manner of your choosing. Uses spells primarily, cast using Wisdom.
* Prophet
Chosen vessel of a particular God. Prophets do not know which God they channel at the beginning of the game. The prophet has a primary mission of discovering which God they are aligned to by learning about the religious system of the world.
* Merchant
Buy low, sell high! Focus on acquiring as much money as possible; making trades and building a reputation across the cities of the world.
* Warrior
Hack, slash, pummel, and dominate your enemies on the way to victory. Uses weapons primarily.
* [[id:7e784143-655d-4170-af49-68aceea59caa][Rogue]]
