:PROPERTIES:
:ID:       940552be-47cf-48ff-8ca0-8c2b7f629052
:END:
#+title:    Paladin
#+filetags: :DND:paladin:
#+author:   zfoteff
#+date:     [2023-08-09 Wed]
#+summary:  Paladin class
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../static/stylesheets/subclass-style.css" />
#+BEGIN_CENTER
[[[id:7d419730-2064-41f9-80ee-f24ed9b01ac7][Main Menu]]] [[[id:69ef1740-156a-4e42-9493-49ec80a4ac26][Classes]]]
#+END_CENTER
-----
Defend the faith and the faithful with the might of your god. Whether sworn before a god's alter in a pristine temple, or in a moment of desperation and grief, a paladin's oath is a powerful bond. Uses heavy weapons and some spellcasting using WIS and CHA. To start as a paladin, first choose a subclass: [[[id:60eb64e5-82ae-42d0-9b3f-e0a662fda360][Holy Knight]], [[id:df760c35-e021-4db3-ba72-4bf457d937fd][Void Priest]], [[id:5afcd93c-8342-4bb3-968c-1d7124b9d93d][Missionary]]]

- Initial Health: Roll 1d10 and add it to your base HP. This is your Hit Die (HD). You will add the amount you roll to your base health every time you level up.

* Proficiencies
| Armor     | Weapons | Tools |
|-----------+---------+-------|
| All armor | Maces   |       |
* Level-up
1. Gain one subclass ability and pick one spell.

   Also gain _Divine Sense_. The presence of strong evil registers on your senses like a harsh sound and powerful good rings like heavenly music. As an action, you can open your awareness to detect such. You can use this feature a number of times equal to 1 + your CHA modifier. You regain all uses on a long rest.
2. Gain. Gain +1 INT and +1 CHA
3. Gain _Divine Smite_: When you hit a creature with a melee weapon attack, you can expend one spell slot to deal Radiant damage to the target in addition to the weapon's regular damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a max of 5d8. The damage increases by 1d8 if the target is undead.
4. Gain +1 to any. Become proficient in an additional class of weapon.
5.
* Footnotes
