:PROPERTIES:
:ID:       b1b752cb-445c-4902-999d-443c83d5113a
:END:
#+title:    Spell Index
#+filetags: :DND:spells:
#+author:   zfoteff
#+date:     [2023-08-08 Tue]
#+summary:  Index of all spells organized into subclasses
#+startup:  show2levels
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../static/stylesheets/default-style.css" />
#+BEGIN_CENTER
[ [[id:49c009a8-dbe3-4867-a616-60c55d87ed54][DM Menu]] ]
#+END_CENTER
-----
* Cantrips
:PROPERTIES:
:ID:       cf1edede-9c94-407b-bfeb-517afcef0ceb
:END:
** Druid Cantrips
:PROPERTIES:
:ID:       b32b2d16-0b71-4af9-9464-b5575f720a99
:END:
- _*Befriend*_: Roll a charisma check. On 14 or higher, turn any non-intelligent creature you are on neutral terms with into an ally. This effect lasts for twenty minutes, after which the creature will enter a state of confusion with a 50% potential to lash out at the party.
- _*Transform*_: Select an animal. From now on, you can transform into this wild animal. Ask the DM about its statistics. One important difference from base DnD rules: the percentage of health that you have stays with you throughout the transformation.
* Spells
:PROPERTIES:
:ID:       9e96d3e7-866f-4393-8ac0-c51a7fcc2500
:END:
** Wizard Spells
:PROPERTIES:
:ID:       59b1702f-8c0c-4152-835f-28689599e262
:END:
** Sorcerer Spells
:PROPERTIES:
:ID:       00bc2086-0ef2-4750-b9c3-bf47ea234f67
:END:
*** Level 1:
- _*Reversion*_: Move all targets within a 20-foot radius to the location they were in the previous turn. This location can be more than 20-feet away from the caster. /You cannot send targets back to other realms with this spell./
- _*Vitality Drain*_: Pick a target  within a 30-foot radius to make a CON saving throw. On failure decrease the target's maximum health by the amount of damage they took in the previous turn. Until combat is over, they are stuck with that maximum health and cannot be healed above it.
- _*Randomness*_: On hit, deal 1d10 of a random type of damage to one target in a 30-foot radius
*** Level 2 (5+):
- _*Retroactive Omen*_: Learn what type of damage a target is vulnerable to. The last three attacks from your allies were now of that damage type. Adjust the target's health accordingly
- _*Return*_: Teleport the party to a place you have been in the past 3 campaign sessions. /Return is non-reversible. You must return to a Temple of Chaos to use the spell again/.
- _*Confuse*_: Force a target within a 50-foot radius to make a CON saving throw. On failure, deal 1d8 damage to them for three turns. For those three turns, the target is confused about who started the fight and will target a random ally of theirs.
*** Level 3 (11+):
- _*Lingering Wound*_: Roll to a hit a target within 30-feet of the caster. On hit, all damage an enemy has previously taken increases by 50%. Ex: If they have taken 10 damage, they take an additional 5 damage
- _*Makeover*_: Change your race, or the race of a consenting ally. This effect does not wear off and only has three charges.
*** Level 4 (16+):
- _*Back to the Future*_: Permanently alter some aspect of the past. This spell has two charges, /you must return to a Temple of Chaos to regain charges/. You must work with the DM to decide how powerful this spell is, but you may change the circumstances of your present to include
  - Revive an ally
  - The death of any enemy that you reasonably could have defeated in combat
  - The prevention of a minor/medium mistake you made
- _*Variety!*_: On hit, deal 10d8 damage - 1d8 of each of the twelve types of damage
